### ISSUE TITLE
problem installing with NuGet

### ISSUE THREAD

**Issue by billwoo** [superlloyd/Galador.Reflection#3]
Hi, I am in a state of brain-fog today :)  I thought I could install by just using NuGet, but:

[Package source] The V2 feed at 'https://www.nuget.org/Search()?$filter=IsAbsoluteLatestVersion&searchTerm='galador.reflection'&targetFramework='net5.0-windows7.0'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.

Not clear what the install process requires.

thanks, Bill

**Comment by superlloyd** [comment]
Oops.. I did the Nuget package a while ago, it probably target .NET4.5 and might not work for .NET 5/6
I will review it tonight.. kind of forget oh the nuget packaging works... 
Can't you use the source in the mean time? (it's just one main source project, and 2 test projects. the android test project might be broken)

**Comment by superlloyd** [comment]
Alright....

1. the README was wrong and I just updated how to serialize/deserialize data
2. a new nuget package has been uploaded, just download Galador.Reflection 1.1.0 from nuget in visual studio
just download with the nuget package explorer, look for Galador.Reflection, version 1.1.0 should be available

**Comment by billwoo** [comment]
Thanks, but ... not yet ... any information I can provide ? It's a WinForm app in Vs 2022/64.

[Package source] The V2 feed at 'https://www.nuget.org/Search()?$filter=IsAbsoluteLatestVersion&searchTerm='n'&targetFramework='net5.0-windows7.0'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.

**Comment by superlloyd** [comment]
Mm… this is very puzzling

To help you, I created a .NET5 Windows Form project using the library, that should help you. It is in the attached zip file.

 

I am not sure where you get your error message… do you use nuget packages usually, from default Microsoft nuget repository?

Because it’s there, look:

https://www.nuget.org/packages/Galador.Reflection/ 

 

Worst comes to worst, you can use the source code from GitHub 😊 
But your nuget is puzzling.. 😲

**Comment by billwoo** [comment]
Thanks !  It looks like the issue is not your project, specifically ... other packages are showing up ... but, an error accessing the V2 server:  I am too burned out to worry about this until tomorrow,

[Package source] The V2 feed at 'https://www.nuget.org/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net5.0-windows7.0'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.
